const NginxConfFile = require('nginx-conf').NginxConfFile;
const commandLineArgs = require('command-line-args');

const options = commandLineArgs([
  { name: 'confpath', alias: 'c', type: String, defaultValue: __dirname + '/nginx.conf'}, //path of nginx.conf file to be updated
  { name: 'tempPath', alias: 't', type: String, defaultValue: '/temps'}, //nginx path for temps. i.e. freenas.local/temp
  { name: 'tempAlias', alias: 'a', type: String, defaultValue: '/mnt/Ocean0/Misc/temperature-monitoring'} //alias path that the temps images are in
]);
try{
  NginxConfFile.create(options.confpath, function(err, conf){
    if(err){
      console.error('Error reading in conf file: ' + err);
      process.exit(2);
    }

    let server = conf.nginx.http.server[0];
    if(server !== undefined){
      for(let i = 0; i < server.location.length; i++){
        let location = server.location[i];
        if(location._value === options.tempPath){
          console.log('Location already exists');
          process.exit(1);
        }
      }

      let locationIndex = server.location.length;
      server._add('location', options.tempPath);
      let location = server.location[locationIndex];
      location._add('alias', options.tempAlias);
      location._comments.push('Auto generated by injectTempGUI');

      conf.flush();
    }
  });
} catch(e){
  console.error('Exception caught: ' + JSON.stringify(e));
  process.exit(2);
}
